baseurl = "https://wdra.ie"
metaDataFormat = "yaml"
title = "Whitehall And Daingean Road Residents Association"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Welcome to the Whitehall And Daingean Road Residents Association site"
      introSubtitle = "Tullamore Co.Offaly"
      introPhoto = "/media/picture.jpg"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1
		
	[[languages.en.menu.main]]
       name = "Newsletter"
       url = "page/newsletter/"
       weight = 2

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Whitehall Residents Association · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"


[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
